# This file was generated by GoReleaser. DO NOT EDIT.
cask "cost-scan" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "51869a43b6345888408ff438d5530d4116e4619eabcecd80c6931f0aff4121c1"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e5f35f78159500c12cd0bd192a6e6a2faf789177983c53f545e4df6b00fd3df"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6962d19e147d440648fd9aa6e5785683f96080574e1c1fb208d05937bb84240a"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c542f943dbc88a0cffd963a0cee1560a57dbd5ee0b037c34b67b93c3a25933aa"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cost-scan"
  desc "Read-only cluster cost waste scanner"
  homepage "https://github.com/DPS0340/cost-scan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cost-scan"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cost-scan"]
    end
  end

  # No zap stanza required

end
