# This file was generated by GoReleaser. DO NOT EDIT.
cask "cost-scan" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "3440f813c566b79deabeb89d732efe5a9e0aaa3f52a253f83bc44c05a6f51475"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ab8909a834d69b3171554322f5eef4d07b2b57bc59975834cb63d79f4dbb699"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dcdd9837d0da7a5fffc9fa6576ff5967712e99b3b5655ec9b07e235dd6cb2400"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b7579a92c64b0422e82db0bdf87bb3e77fc6d3910f061aa7b60e5a5d5471012"
      url "https://github.com/DPS0340/cost-scan/releases/download/v#{version}/cost-scan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cost-scan"
  desc "Read-only cluster cost waste scanner"
  homepage "https://github.com/DPS0340/cost-scan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cost-scan"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cost-scan"]
    end
  end

  # No zap stanza required

end
