# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeoptimizer" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "6817af8d4c7ac5a309a5c22290737f350b2d54c88362b92e725592c02ecc4ad2"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3593865a31525401c1df161c2bbfd54c8742a31a09bab60e1607fd1e5fd72a4"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cbf20dd02f8542db2b3ee0c144170925e831455c54f6a83d0a7b6728b6af21a2"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61ebff20583fafb620b984f6202cd81b7140d9737602ff60fc2d2d0f7e3ad10d"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubeoptimizer"
  desc "Read-only Kubernetes cost waste scanner"
  homepage "https://github.com/DPS0340/kubeoptimizer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeoptimizer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeoptimizer"]
    end
  end

  # No zap stanza required

end
