# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeoptimizer" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f582da124eaca689dff53355e7194eec60c59b8caee1be45c2efbfc2646f8e9f"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "64f5a0b7a7c0e891faeddc2cd0ebf90e15728ed9badd78c599746f365c73ec71"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2e4531fa1b144ced5e393c5ea9aad807947ed37ed1fbda1df4f7dcae92fd6a9"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1c1fafead5cae998a945f5b3e43fb195ab9515f83f5082a2ae7c8d1a6120fbc"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubeoptimizer"
  desc "Read-only Kubernetes cost waste scanner"
  homepage "https://github.com/DPS0340/kubeoptimizer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeoptimizer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeoptimizer"]
    end
  end

  # No zap stanza required

end
