# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeoptimizer" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d5edaf620723bb7baee8a6a8173ca09d305c17bdd14e8db23f6cf7c1b1838a63"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b07b4cca80a12fb1bd851fb1efdeea7f2ed1c29107fe8cda2ef0b92476fb4e0a"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a2a5045c66d6bd1d70c034e056d86b64eaf6d829b57f53437e00bd80d28b994"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "747ebaadbe648d8f8723dd01b64aefafe9dee1854d389135a1ebded46f69c27e"
      url "https://github.com/DPS0340/kubeoptimizer/releases/download/v#{version}/kubeoptimizer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubeoptimizer"
  desc "Read-only Kubernetes cost waste scanner"
  homepage "https://github.com/DPS0340/kubeoptimizer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeoptimizer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeoptimizer"]
    end
  end

  # No zap stanza required

end
