# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenaudit" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "7492cff48372f6096248c253c371c14304a0f57a74b0d680ec231b70bf5ed376"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d96dbf7d7f625cab4210540d1ad5a4d3e3ca99e6dfa25a4e5fabef80205eeffb"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5728bcc742bf2d4a55e65cddf87cdf741bbd384b9b7ec357a158a43a1c93eab0"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a803617f8efcba10381f94eb10838fd593e59aecffdb2d6a692e97381eee84e"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tokenaudit"
  desc "Read-only LLM API cost waste scanner"
  homepage "https://github.com/DPS0340/tokenaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenaudit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokenaudit"]
    end
  end

  # No zap stanza required

end
