# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenaudit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6cd0f19004250a45f786369d09be04cd5383772d06d0db89f88e975e65ec969d"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4586b2987f103d4902c872e4d256722217dad7e38bb289355326181199c3b8d6"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "793f64487c0838189bc8400ea464698352e06de25c4aa96264c4dd6e07818720"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6fb92843f69ccf1b90c5f0b4343b211e45b12bfb3a7614e68d559f5282d4273"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tokenaudit"
  desc "Read-only LLM API cost waste scanner"
  homepage "https://github.com/DPS0340/tokenaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenaudit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokenaudit"]
    end
  end

  # No zap stanza required

end
