# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenaudit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "cd820463159f6f02dd0c36e677874cf7cc803884aafb82d0b41a9a530f607cef"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8a125596de993e22a136abb7b61f5574d504aceecff7e40b7c55ec2e45e320ca"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "28984a3ad31aa50a8ee93981ffa21f0f59e79684022001fff260a9a246973f1d"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f821de26ba0acba7d95f5b06082b343d188c266e3e82d97f22744423f4350bb2"
      url "https://github.com/DPS0340/tokenaudit/releases/download/v#{version}/tokenaudit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tokenaudit"
  desc "Read-only LLM API cost waste scanner"
  homepage "https://github.com/DPS0340/tokenaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenaudit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokenaudit"]
    end
  end

  # No zap stanza required

end
